### ISSUE TITLE
Update go-cassandra-native-protocol dependency

### ISSUE THREAD

**Issue by StevenLacerda** [datastax/cql-proxy#116]
IHAC that ran into an issue with what looks like a dependency issue in go-cassandra-native-protocol:

```
# github.com/datastax/cql-proxy/parser
/go/pkg/mod/github.com/datastax/cql-proxy@v0.1.4/parser/metadata.go:28:71: undefined: datatype.NewSetType
/go/pkg/mod/github.com/datastax/cql-proxy@v0.1.4/parser/metadata.go:46:71: undefined: datatype.NewSetType
/go/pkg/mod/github.com/datastax/cql-proxy@v0.1.4/parser/metadata.go:61:71: undefined: datatype.NewSetType
/go/pkg/mod/github.com/datastax/cql-proxy@v0.1.4/parser/metadata.go:73:71: undefined: datatype.NewSetType
/go/pkg/mod/github.com/datastax/cql-proxy@v0.1.4/parser/metadata.go:99:96: undefined: datatype.NewMapType
/go/pkg/mod/github.com/datastax/cql-proxy@v0.1.4/parser/metadata.go:130:87: undefined: datatype.NewListType
/go/pkg/mod/github.com/datastax/cql-proxy@v0.1.4/parser/metadata.go:131:87: undefined: datatype.NewListType
```

@absurdfarce FYI

**Comment by absurdfarce** [comment]
Re-posting comments from analysis of the above from elsewhere.

Looks like the problem here is that the [dependency on go-cassandra-native-protocol](https://github.com/datastax/cql-proxy/blob/main/go.mod#L8) is pretty old now.  Specifically it's from before [this commit](https://github.com/datastax/go-cassandra-native-protocol/commit/796e2ddab33f84d52082932cd322e02410944bed) which changes around a few function names.

If an application is using [gocql-astra](https://github.com/datastax/gocql-astra) they'll bring in cql-proxy (for SCB handling) which in turn will bring in this older version of go-cassandra-native-protocol.  If the application in question is already using a more recent version of go-cassandra-native-protocol from somewhere else you could quite possibly wind up with the build errors referenced above.

Safest bet is probably to update cql-proxy to use the latest go-cassandra-native-protocol.

Longer-term we can also look at decoupling cql-proxy from gocql-astra along the lines of what's discussed [here](https://github.com/datastax/cql-proxy/issues/115).

**Comment by absurdfarce** [comment]
Note that there's a similar issue for [astra-client-go](https://github.com/datastax/astra-client-go).  cql-proxy currently brings in 2.2.9 of this lib while most recent is 2.2.48.

**Comment by absurdfarce** [comment]
@synedra For the case which brought on this ticket the solution was to remove the explicit dependency on go-cassandra-native-protocol and use the version that comes in via cql-proxy by way of gocql-astra.  It's definitely both hacky and patchy but it should get you unstuck.

You'll likely have some code changes if you were using the most recent go-cassandra-native-protocol due to some changes to the API in versions between what cql-proxy brings along and whatever's on HEAD... but any such changes _should_ be fairly minor.

cc @joao-r-reis
